name: Deploy Storybook
on:
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/upload-pages-artifact@v2
        with:
          path: 'storybook-static/'  # Путь к распакованным файлам
      - uses: actions/deploy-pages@v3
